from __future__ import annotations

# Stack Overflow 質問のテキストマイニングで頻出するが意味を持たない語
# 一般的な英語ストップワードに加えて、プログラミング文書固有の語を除外する
DOMAIN_STOPWORDS: set[str] = {
    "use",
    "using",
    "used",
    "get",
    "getting",
    "got",
    "want",
    "need",
    "like",
    "know",
    "work",
    "working",
    "run",
    "running",
    "make",
    "try",
    "trying",
    "call",
    "calling",
    "return",
    "set",
    "add",
    "check",
    "code",
    "function",
    "variable",
    "value",
    "type",
    "object",
    "class",
    "method",
    "print",
    "data",
    "file",
    "list",
    "string",
    "number",
    "output",
    "input",
    "result",
    "answer",
    "question",
    "example",
    "following",
    "below",
    "above",
    "way",
    "possible",
    "help",
}
